module.exports = {
    "pikachu": "Pikachu is an Electric-type Pokémon. It evolves from Pichu and evolves into Raichu.",
    "charizard": "Charizard is a dual-type Fire/Flying Pokémon. It evolves from Charmeleonand is final form of Charmander.",
    "mewtwo": "Mewtwo is a Psychic-type Legendary Pokémon. It can Mega Evolve into two different forms.", 
    "dragonite": "Dragonite is a dual-type Dragon/Flying pseudo-legendary Pokémon. It evolves from Dragonair and is the final form of Dratini.",
    "snorlax": "Snorlax is a Normal-type Pokémon. It evolves from Munchlax when leveled up with high friendship.",
    "lapras": "Lapras is a dual-type Water/Ice Pokémon. It is not known to evolve into or from any other Pokémon.",
    "arcanine": "Arcanine is a Fire-type Pokémon. It evolves from Growlithe when exposed to a Fire Stone.",
    "exeggutor": "Exeggutor is a dual-type Grass/Psychic Pokémon. It evolves from Exeggcute when exposed to a Leaf Stone.",
    "blastoise": "Blastoise is a Water-type Pokémon. It evolves from Wartortle and is the final form of Squirtle.",
    "gyrados": "Gyarados is a dual-type Water/Flying Pokémon. It evolves from Magikarp",
    "ninetales": "Ninetales is a Fire-type Pokémon. It evolves from Vulpix when exposed to a Fire Stone.",
    "pinsir": "Pinsir is a Bug-type Pokémon. It is not known to evolve into or from any other Pokémon",
    "scyther": "Scyther is a dual-type Bug/Flying Pokémon.",
    "aerodactyl": "Aerodactyl is a dual-type Rock/Flying Fossil Pokémon. It is not known to evolve into or from any other Pokémon",
    "pidgy": "Pidgy is a dual-type Normal/Flying Pokémon. It evolves into Pidgeotto which evolves into Pidgeot.",
    "bulbasaur": "Bulbasaur is a dual-type Grass/Poison Pokémon. It evolves into Ivysaurwhich evolves into Venusaur.",
    "caterpie": "Caterpie is a Bug-type Pokémon. It evolves into Metapod which evolves into Butterfree",
    "weedle": "Weedle is a dual-type Bug/Poison Pokémon. It evolves into Kakuna which evolves into Beedrill",
    "rattata": "Rattata is a Normal-type Pokémon. It evolves into Raticate.",
    "spearow": "Spearow is a dual-type Normal/Flying Pokémon. It evolves into Fearow.",
    "ekans": "Ekans is a Poison-type Pokémon. It evolves into Arbok.",
    "sandshrew": "Sandshrew is a Ground-type Pokémon. It evolves into Sandslash",
    "paras": "Paras is a dual-type Bug/Grass Pokémon. It evolves into Parasect.",
    "koffing": "Koffing is a Poison-type Pokémon. It evolves into Weezing."
};
